namespace Exemplos.Clinica {
    export interface AutorizacoesRow {
        AutorizacaoId?: number;
        NumeroAutorizacao?: string;
        ConvenioId?: number;
        PacienteId?: number;
        Arquivos?: string;
        DataSolicitacao?: string;
        DataAutorizacao?: string;
        DataValidade?: string;
        Observacao?: string;
        IdAuditoriaAprovada?: boolean;
        ConvenioCnpj?: string;
        ConvenioRazaoSocial?: string;
        ConvenioNomeFantasia?: string;
        ConvenioCodigoAns?: string;
        ConvenioCadastroConvenio?: string;
        ConvenioLogo?: string;
        ConvenioInscricaoMunicipal?: string;
        ConvenioInscricaoEstadual?: string;
        ConvenioSite?: string;
        ConvenioDataInicio?: string;
        ConvenioInativo?: boolean;
        ConvenioDataFim?: string;
        ConvenioMotivoCancelamento?: string;
        ConvenioObservacao?: string;
        ConvenioVersaoTiss?: string;
        ConvenioWebService?: string;
        ConvenioSadtSolContratadoId?: string;
        ConvenioSadtExecutanteId?: string;
        ConvenioSadtProfissionalexecutante?: string;
        ConvenioSadtMembroEquipe?: string;
        ConvenioIdOrigem?: string;
        ConvenioIdDestino?: string;
        ConvenioOrigemIdPrestador?: string;
        ConvenioDestinoIdPrestador?: string;
        ConvenioIdLogo?: number;
        ConvenioGeraTiss?: boolean;
        ConvenioDataCadastro?: string;
        ConvenioDataUltimaAtualizacao?: string;
        ConvenioLatitude?: string;
        ConvenioLongitude?: string;
        ConvenioEmailNotaFiscal?: string;
        ConvenioEmailContato?: string;
        ConvenioEmailFaturamento?: string;
        ConvenioEmailGlosa?: string;
        PacienteDataCadastro?: string;
        PacienteDataUltimaAtualizacao?: string;
        PacienteMatricula?: string;
        PacienteStatusId?: number;
        Paciente?: string;
        PacienteEspecial?: boolean;
        PacientePai?: string;
        PacienteMae?: string;
        PacienteSexoId?: number;
        PacienteDataNascimento?: string;
        PacienteCns?: string;
        PacienteCarteiraIdentidade?: string;
        PacienteCpf?: string;
        PacienteObservacao?: string;
        PacienteDisturbiosAssociados?: string;
        PacienteResponsavel?: string;
        PacienteNotaFiscalTerceiro?: boolean;
        PacienteNotaFiscalNome?: string;
        PacienteNotaFiscalCpf?: string;
        PacienteNotaFiscalCnpj?: string;
        PacienteNotaFiscalEndereco?: string;
        PacienteNotaFiscalNumero?: string;
        PacienteNotaFiscalBairro?: string;
        PacienteNotaFiscalCidade?: string;
        PacienteNotaFiscalEstadoId?: string;
        PacienteNotaFiscalEmail?: string;
        PacienteFoto?: string;
        PacienteDataFoto?: string;
        PacientePacienteIdControlMedic?: number;
        PacientePacienteIdGestorMedico?: number;
    }

    export namespace AutorizacoesRow {
        export const idProperty = 'AutorizacaoId';
        export const nameProperty = 'NumeroAutorizacao';
        export const localTextPrefix = 'Clinica.Autorizacoes';
        export const lookupKey = 'Clinica.Autorizacoes';

        export function getLookup(): Q.Lookup<AutorizacoesRow> {
            return Q.getLookup<AutorizacoesRow>('Clinica.Autorizacoes');
        }

        export namespace Fields {
            export declare const AutorizacaoId: string;
            export declare const NumeroAutorizacao: string;
            export declare const ConvenioId: string;
            export declare const PacienteId: string;
            export declare const Arquivos: string;
            export declare const DataSolicitacao: string;
            export declare const DataAutorizacao: string;
            export declare const DataValidade: string;
            export declare const Observacao: string;
            export declare const IdAuditoriaAprovada: string;
            export declare const ConvenioCnpj: string;
            export declare const ConvenioRazaoSocial: string;
            export declare const ConvenioNomeFantasia: string;
            export declare const ConvenioCodigoAns: string;
            export declare const ConvenioCadastroConvenio: string;
            export declare const ConvenioLogo: string;
            export declare const ConvenioInscricaoMunicipal: string;
            export declare const ConvenioInscricaoEstadual: string;
            export declare const ConvenioSite: string;
            export declare const ConvenioDataInicio: string;
            export declare const ConvenioInativo: string;
            export declare const ConvenioDataFim: string;
            export declare const ConvenioMotivoCancelamento: string;
            export declare const ConvenioObservacao: string;
            export declare const ConvenioVersaoTiss: string;
            export declare const ConvenioWebService: string;
            export declare const ConvenioSadtSolContratadoId: string;
            export declare const ConvenioSadtExecutanteId: string;
            export declare const ConvenioSadtProfissionalexecutante: string;
            export declare const ConvenioSadtMembroEquipe: string;
            export declare const ConvenioIdOrigem: string;
            export declare const ConvenioIdDestino: string;
            export declare const ConvenioOrigemIdPrestador: string;
            export declare const ConvenioDestinoIdPrestador: string;
            export declare const ConvenioIdLogo: string;
            export declare const ConvenioGeraTiss: string;
            export declare const ConvenioDataCadastro: string;
            export declare const ConvenioDataUltimaAtualizacao: string;
            export declare const ConvenioLatitude: string;
            export declare const ConvenioLongitude: string;
            export declare const ConvenioEmailNotaFiscal: string;
            export declare const ConvenioEmailContato: string;
            export declare const ConvenioEmailFaturamento: string;
            export declare const ConvenioEmailGlosa: string;
            export declare const PacienteDataCadastro: string;
            export declare const PacienteDataUltimaAtualizacao: string;
            export declare const PacienteMatricula: string;
            export declare const PacienteStatusId: string;
            export declare const Paciente: string;
            export declare const PacienteEspecial: string;
            export declare const PacientePai: string;
            export declare const PacienteMae: string;
            export declare const PacienteSexoId: string;
            export declare const PacienteDataNascimento: string;
            export declare const PacienteCns: string;
            export declare const PacienteCarteiraIdentidade: string;
            export declare const PacienteCpf: string;
            export declare const PacienteObservacao: string;
            export declare const PacienteDisturbiosAssociados: string;
            export declare const PacienteResponsavel: string;
            export declare const PacienteNotaFiscalTerceiro: string;
            export declare const PacienteNotaFiscalNome: string;
            export declare const PacienteNotaFiscalCpf: string;
            export declare const PacienteNotaFiscalCnpj: string;
            export declare const PacienteNotaFiscalEndereco: string;
            export declare const PacienteNotaFiscalNumero: string;
            export declare const PacienteNotaFiscalBairro: string;
            export declare const PacienteNotaFiscalCidade: string;
            export declare const PacienteNotaFiscalEstadoId: string;
            export declare const PacienteNotaFiscalEmail: string;
            export declare const PacienteFoto: string;
            export declare const PacienteDataFoto: string;
            export declare const PacientePacienteIdControlMedic: string;
            export declare const PacientePacienteIdGestorMedico: string;
        }

        ['AutorizacaoId', 'NumeroAutorizacao', 'ConvenioId', 'PacienteId', 'Arquivos', 'DataSolicitacao', 'DataAutorizacao', 'DataValidade', 'Observacao', 'IdAuditoriaAprovada', 'ConvenioCnpj', 'ConvenioRazaoSocial', 'ConvenioNomeFantasia', 'ConvenioCodigoAns', 'ConvenioCadastroConvenio', 'ConvenioLogo', 'ConvenioInscricaoMunicipal', 'ConvenioInscricaoEstadual', 'ConvenioSite', 'ConvenioDataInicio', 'ConvenioInativo', 'ConvenioDataFim', 'ConvenioMotivoCancelamento', 'ConvenioObservacao', 'ConvenioVersaoTiss', 'ConvenioWebService', 'ConvenioSadtSolContratadoId', 'ConvenioSadtExecutanteId', 'ConvenioSadtProfissionalexecutante', 'ConvenioSadtMembroEquipe', 'ConvenioIdOrigem', 'ConvenioIdDestino', 'ConvenioOrigemIdPrestador', 'ConvenioDestinoIdPrestador', 'ConvenioIdLogo', 'ConvenioGeraTiss', 'ConvenioDataCadastro', 'ConvenioDataUltimaAtualizacao', 'ConvenioLatitude', 'ConvenioLongitude', 'ConvenioEmailNotaFiscal', 'ConvenioEmailContato', 'ConvenioEmailFaturamento', 'ConvenioEmailGlosa', 'PacienteDataCadastro', 'PacienteDataUltimaAtualizacao', 'PacienteMatricula', 'PacienteStatusId', 'Paciente', 'PacienteEspecial', 'PacientePai', 'PacienteMae', 'PacienteSexoId', 'PacienteDataNascimento', 'PacienteCns', 'PacienteCarteiraIdentidade', 'PacienteCpf', 'PacienteObservacao', 'PacienteDisturbiosAssociados', 'PacienteResponsavel', 'PacienteNotaFiscalTerceiro', 'PacienteNotaFiscalNome', 'PacienteNotaFiscalCpf', 'PacienteNotaFiscalCnpj', 'PacienteNotaFiscalEndereco', 'PacienteNotaFiscalNumero', 'PacienteNotaFiscalBairro', 'PacienteNotaFiscalCidade', 'PacienteNotaFiscalEstadoId', 'PacienteNotaFiscalEmail', 'PacienteFoto', 'PacienteDataFoto', 'PacientePacienteIdControlMedic', 'PacientePacienteIdGestorMedico'].forEach(x => (<any>Fields)[x] = x);
    }
}

