namespace Exemplos.Clinica {
    export interface SessoesRow {
        SessaoId?: number;
        IdPrimeiraSessao?: boolean;
        OrdemSessao?: number;
        GuiaId?: number;
        AgendaItemId?: number;
        LoteId?: number;
        StatusSessaoId?: number;
        ProfissionalIdExecutante?: number;
        ValorId?: number;
        TipoItemId?: number;
        TipoTabelaId?: number;
        ProcedimentoId?: number;
        ConvenioId?: number;
        CodigoProcedimento?: string;
        Procedimento?: string;
        ValorSessao?: number;
        QuantidadeSessao?: number;
        ReducaoAcrescimo?: number;
        DataSessao?: string;
        HoraInicioSessao?: string;
        HoraFimSessao?: string;
        ValorPago?: number;
        DataPago?: string;
        ValorGlosado?: number;
        CodigoGlosa?: string;
        MotivoGlosa?: string;
        StatusGlosaId?: number;
        ProtocoloRecurso?: string;
        DataRecurso?: string;
        Recurso?: string;
        DataRespostaRecurso?: string;
        SituacaoRespostaRecurso?: string;
        RespostaRecurso?: string;
        ValorRecursoPago?: number;
        ProtocoloUltimoRecurso?: string;
        DataUltimoRecurso?: string;
        UltimoRecurso?: string;
        DataRespostaUltimoRecurso?: string;
        SituacaoRespostaUltimoRecurso?: string;
        RespostaUltimoRecurso?: string;
        ValorUltimoRecursoPago?: number;
        QuantidadeRecursos?: number;
        Observacoes?: string;
        SequenciaItens?: number;
        Sequencia?: number;
        DemonstrativoItemId?: number;
        DemonstrativoItemIdGlosa?: number;
        IdAuditada?: boolean;
        DataAuditoria?: string;
        IdAuditoriaAprovada?: boolean;
        ConclusaoAuditoria?: string;
        IdPagoProfissional?: boolean;
        ValorFixo?: boolean;
        PorcentagemAplicadaProfissional?: number;
        ValorPagoProfissional?: number;
        DataPagoProfissional?: string;
        FolhaPagamentoProfissionalId?: number;
        AgendaItemTipoGuiaId?: number;
        AgendaItemTipoConsultaId?: number;
        AgendaItemGuia?: string;
        AgendaItemGuiaOperador?: string;
        AgendaItemCarteirinha?: string;
        AgendaItemNomePaciente?: string;
        AgendaItemAutorizacaoId?: number;
        AgendaItemNumeroAutorizacao?: string;
        AgendaItemIdAuditada?: boolean;
        AgendaItemDataAuditoria?: string;
        AgendaItemIdAuditoriaAprovada?: boolean;
        AgendaItemConclusaoAuditoria?: string;
        AgendaItemProfissionalIdSolicitante?: number;
        AgendaItemProfissionalIdExecutante?: number;
        LoteStatusLoteId?: number;
        LoteMovimentacao?: string;
        LoteConvenioId?: number;
        LoteDataEmissaoLote?: string;
        Lote?: string;
        LoteProtocolo?: string;
        LoteLoteConvenio?: string;
        LoteValorLote?: number;
        LoteCapaLote?: string;
        LoteExtrato?: string;
        LoteEnviadoConvenioId?: boolean;
        LoteDataEnviadoConvenio?: string;
        LoteArquivoFisicoEnviadoId?: boolean;
        LoteCartaSimplesId?: boolean;
        LoteSedex?: string;
        LoteArid?: boolean;
        LoteDataRetornoAr?: string;
        LoteValorCorreios?: number;
        LoteArquivos?: string;
        LoteObservacao?: string;
        LoteNfseid?: number;
        LoteNotaFiscal?: string;
        LoteValorNotaFiscal?: number;
        LoteDataEmissaoNotaFiscal?: string;
        LoteEmailNotaFiscal?: string;
        LoteNotaFiscalImpressaId?: boolean;
        LoteNotaFiscalRecebida?: string;
        LoteDataNotaFiscalImpressa?: string;
        StatusSessaoStatus?: string;
        ValorTipoItemId?: number;
        ValorTipoTabelaId?: number;
        ValorProcedimentoId?: number;
        ValorConvenioId?: number;
        ValorValorCh?: number;
        ValorValorSessao?: number;
        ValorDataInicio?: string;
        ValorDataFim?: string;
        ValorObservacao?: string;
        ValorDataCadastrada?: string;
        ValorCodigoRegistrado?: boolean;
        ValorRequerAutorizacao?: boolean;
        ValorTipoAutorizacaoId?: number;
        FolhaPagamentoProfissionalProfissionalId?: number;
        FolhaPagamentoProfissionalNotaFiscalProfissional?: number;
        FolhaPagamentoProfissionalArquivos?: string;
        FolhaPagamentoProfissionalMovimento?: string;
        FolhaPagamentoProfissionalDataPagamento?: string;
        FolhaPagamentoProfissionalValorPago?: number;
        FolhaPagamentoProfissionalDataImpressao?: string;
    }

    export namespace SessoesRow {
        export const idProperty = 'SessaoId';
        export const nameProperty = 'CodigoProcedimento';
        export const localTextPrefix = 'Clinica.Sessoes';
        export const lookupKey = 'Clinica.Sessoes';

        export function getLookup(): Q.Lookup<SessoesRow> {
            return Q.getLookup<SessoesRow>('Clinica.Sessoes');
        }

        export namespace Fields {
            export declare const SessaoId: string;
            export declare const IdPrimeiraSessao: string;
            export declare const OrdemSessao: string;
            export declare const GuiaId: string;
            export declare const AgendaItemId: string;
            export declare const LoteId: string;
            export declare const StatusSessaoId: string;
            export declare const ProfissionalIdExecutante: string;
            export declare const ValorId: string;
            export declare const TipoItemId: string;
            export declare const TipoTabelaId: string;
            export declare const ProcedimentoId: string;
            export declare const ConvenioId: string;
            export declare const CodigoProcedimento: string;
            export declare const Procedimento: string;
            export declare const ValorSessao: string;
            export declare const QuantidadeSessao: string;
            export declare const ReducaoAcrescimo: string;
            export declare const DataSessao: string;
            export declare const HoraInicioSessao: string;
            export declare const HoraFimSessao: string;
            export declare const ValorPago: string;
            export declare const DataPago: string;
            export declare const ValorGlosado: string;
            export declare const CodigoGlosa: string;
            export declare const MotivoGlosa: string;
            export declare const StatusGlosaId: string;
            export declare const ProtocoloRecurso: string;
            export declare const DataRecurso: string;
            export declare const Recurso: string;
            export declare const DataRespostaRecurso: string;
            export declare const SituacaoRespostaRecurso: string;
            export declare const RespostaRecurso: string;
            export declare const ValorRecursoPago: string;
            export declare const ProtocoloUltimoRecurso: string;
            export declare const DataUltimoRecurso: string;
            export declare const UltimoRecurso: string;
            export declare const DataRespostaUltimoRecurso: string;
            export declare const SituacaoRespostaUltimoRecurso: string;
            export declare const RespostaUltimoRecurso: string;
            export declare const ValorUltimoRecursoPago: string;
            export declare const QuantidadeRecursos: string;
            export declare const Observacoes: string;
            export declare const SequenciaItens: string;
            export declare const Sequencia: string;
            export declare const DemonstrativoItemId: string;
            export declare const DemonstrativoItemIdGlosa: string;
            export declare const IdAuditada: string;
            export declare const DataAuditoria: string;
            export declare const IdAuditoriaAprovada: string;
            export declare const ConclusaoAuditoria: string;
            export declare const IdPagoProfissional: string;
            export declare const ValorFixo: string;
            export declare const PorcentagemAplicadaProfissional: string;
            export declare const ValorPagoProfissional: string;
            export declare const DataPagoProfissional: string;
            export declare const FolhaPagamentoProfissionalId: string;
            export declare const AgendaItemTipoGuiaId: string;
            export declare const AgendaItemTipoConsultaId: string;
            export declare const AgendaItemGuia: string;
            export declare const AgendaItemGuiaOperador: string;
            export declare const AgendaItemCarteirinha: string;
            export declare const AgendaItemNomePaciente: string;
            export declare const AgendaItemAutorizacaoId: string;
            export declare const AgendaItemNumeroAutorizacao: string;
            export declare const AgendaItemIdAuditada: string;
            export declare const AgendaItemDataAuditoria: string;
            export declare const AgendaItemIdAuditoriaAprovada: string;
            export declare const AgendaItemConclusaoAuditoria: string;
            export declare const AgendaItemProfissionalIdSolicitante: string;
            export declare const AgendaItemProfissionalIdExecutante: string;
            export declare const LoteStatusLoteId: string;
            export declare const LoteMovimentacao: string;
            export declare const LoteConvenioId: string;
            export declare const LoteDataEmissaoLote: string;
            export declare const Lote: string;
            export declare const LoteProtocolo: string;
            export declare const LoteLoteConvenio: string;
            export declare const LoteValorLote: string;
            export declare const LoteCapaLote: string;
            export declare const LoteExtrato: string;
            export declare const LoteEnviadoConvenioId: string;
            export declare const LoteDataEnviadoConvenio: string;
            export declare const LoteArquivoFisicoEnviadoId: string;
            export declare const LoteCartaSimplesId: string;
            export declare const LoteSedex: string;
            export declare const LoteArid: string;
            export declare const LoteDataRetornoAr: string;
            export declare const LoteValorCorreios: string;
            export declare const LoteArquivos: string;
            export declare const LoteObservacao: string;
            export declare const LoteNfseid: string;
            export declare const LoteNotaFiscal: string;
            export declare const LoteValorNotaFiscal: string;
            export declare const LoteDataEmissaoNotaFiscal: string;
            export declare const LoteEmailNotaFiscal: string;
            export declare const LoteNotaFiscalImpressaId: string;
            export declare const LoteNotaFiscalRecebida: string;
            export declare const LoteDataNotaFiscalImpressa: string;
            export declare const StatusSessaoStatus: string;
            export declare const ValorTipoItemId: string;
            export declare const ValorTipoTabelaId: string;
            export declare const ValorProcedimentoId: string;
            export declare const ValorConvenioId: string;
            export declare const ValorValorCh: string;
            export declare const ValorValorSessao: string;
            export declare const ValorDataInicio: string;
            export declare const ValorDataFim: string;
            export declare const ValorObservacao: string;
            export declare const ValorDataCadastrada: string;
            export declare const ValorCodigoRegistrado: string;
            export declare const ValorRequerAutorizacao: string;
            export declare const ValorTipoAutorizacaoId: string;
            export declare const FolhaPagamentoProfissionalProfissionalId: string;
            export declare const FolhaPagamentoProfissionalNotaFiscalProfissional: string;
            export declare const FolhaPagamentoProfissionalArquivos: string;
            export declare const FolhaPagamentoProfissionalMovimento: string;
            export declare const FolhaPagamentoProfissionalDataPagamento: string;
            export declare const FolhaPagamentoProfissionalValorPago: string;
            export declare const FolhaPagamentoProfissionalDataImpressao: string;
        }

        ['SessaoId', 'IdPrimeiraSessao', 'OrdemSessao', 'GuiaId', 'AgendaItemId', 'LoteId', 'StatusSessaoId', 'ProfissionalIdExecutante', 'ValorId', 'TipoItemId', 'TipoTabelaId', 'ProcedimentoId', 'ConvenioId', 'CodigoProcedimento', 'Procedimento', 'ValorSessao', 'QuantidadeSessao', 'ReducaoAcrescimo', 'DataSessao', 'HoraInicioSessao', 'HoraFimSessao', 'ValorPago', 'DataPago', 'ValorGlosado', 'CodigoGlosa', 'MotivoGlosa', 'StatusGlosaId', 'ProtocoloRecurso', 'DataRecurso', 'Recurso', 'DataRespostaRecurso', 'SituacaoRespostaRecurso', 'RespostaRecurso', 'ValorRecursoPago', 'ProtocoloUltimoRecurso', 'DataUltimoRecurso', 'UltimoRecurso', 'DataRespostaUltimoRecurso', 'SituacaoRespostaUltimoRecurso', 'RespostaUltimoRecurso', 'ValorUltimoRecursoPago', 'QuantidadeRecursos', 'Observacoes', 'SequenciaItens', 'Sequencia', 'DemonstrativoItemId', 'DemonstrativoItemIdGlosa', 'IdAuditada', 'DataAuditoria', 'IdAuditoriaAprovada', 'ConclusaoAuditoria', 'IdPagoProfissional', 'ValorFixo', 'PorcentagemAplicadaProfissional', 'ValorPagoProfissional', 'DataPagoProfissional', 'FolhaPagamentoProfissionalId', 'AgendaItemTipoGuiaId', 'AgendaItemTipoConsultaId', 'AgendaItemGuia', 'AgendaItemGuiaOperador', 'AgendaItemCarteirinha', 'AgendaItemNomePaciente', 'AgendaItemAutorizacaoId', 'AgendaItemNumeroAutorizacao', 'AgendaItemIdAuditada', 'AgendaItemDataAuditoria', 'AgendaItemIdAuditoriaAprovada', 'AgendaItemConclusaoAuditoria', 'AgendaItemProfissionalIdSolicitante', 'AgendaItemProfissionalIdExecutante', 'LoteStatusLoteId', 'LoteMovimentacao', 'LoteConvenioId', 'LoteDataEmissaoLote', 'Lote', 'LoteProtocolo', 'LoteLoteConvenio', 'LoteValorLote', 'LoteCapaLote', 'LoteExtrato', 'LoteEnviadoConvenioId', 'LoteDataEnviadoConvenio', 'LoteArquivoFisicoEnviadoId', 'LoteCartaSimplesId', 'LoteSedex', 'LoteArid', 'LoteDataRetornoAr', 'LoteValorCorreios', 'LoteArquivos', 'LoteObservacao', 'LoteNfseid', 'LoteNotaFiscal', 'LoteValorNotaFiscal', 'LoteDataEmissaoNotaFiscal', 'LoteEmailNotaFiscal', 'LoteNotaFiscalImpressaId', 'LoteNotaFiscalRecebida', 'LoteDataNotaFiscalImpressa', 'StatusSessaoStatus', 'ValorTipoItemId', 'ValorTipoTabelaId', 'ValorProcedimentoId', 'ValorConvenioId', 'ValorValorCh', 'ValorValorSessao', 'ValorDataInicio', 'ValorDataFim', 'ValorObservacao', 'ValorDataCadastrada', 'ValorCodigoRegistrado', 'ValorRequerAutorizacao', 'ValorTipoAutorizacaoId', 'FolhaPagamentoProfissionalProfissionalId', 'FolhaPagamentoProfissionalNotaFiscalProfissional', 'FolhaPagamentoProfissionalArquivos', 'FolhaPagamentoProfissionalMovimento', 'FolhaPagamentoProfissionalDataPagamento', 'FolhaPagamentoProfissionalValorPago', 'FolhaPagamentoProfissionalDataImpressao'].forEach(x => (<any>Fields)[x] = x);
    }
}

